"""Add author_name to NewsArticle

Revision ID: 3abe91512295
Revises: 009_force_drop_video_type
Create Date: 2026-06-05 09:26:35.304909
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3abe91512295'
down_revision: Union[str, None] = '009_force_drop_video_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_permissions', 'admin_role',
               existing_type=postgresql.ENUM('super_admin', 'content_admin', 'finance_admin', 'support_admin', name='admin_role_type'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('lectures', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('lectures_course_id_fkey', 'lectures', type_='foreignkey')
    op.create_foreign_key(None, 'lectures', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'lectures', type_='foreignkey')
    op.create_foreign_key('lectures_course_id_fkey', 'lectures', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('lectures', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('admin_permissions', 'admin_role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('super_admin', 'content_admin', 'finance_admin', 'support_admin', name='admin_role_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
