"""Add author_name to NewsArticle

Revision ID: 3abe91512295
Revises: 009_force_drop_video_type
Create Date: 2026-06-05 09:26:35.304909
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3abe91512295'
down_revision: Union[str, None] = '009_force_drop_video_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    tables = insp.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'admin_permissions' in tables:
        cols = insp.get_columns('admin_permissions')
        admin_role_col = next((c for c in cols if c['name'] == 'admin_role'), None)
        if admin_role_col and not isinstance(admin_role_col['type'], sa.String):
            op.alter_column('admin_permissions', 'admin_role',
                       existing_type=postgresql.ENUM('super_admin', 'content_admin', 'finance_admin', 'support_admin', name='admin_role_type'),
                       type_=sa.String(length=50),
                       existing_nullable=False)

    if 'lectures' in tables:
        cols = insp.get_columns('lectures')
        course_id_col = next((c for c in cols if c['name'] == 'course_id'), None)
        if course_id_col and not course_id_col['nullable']:
            op.alter_column('lectures', 'course_id',
                       existing_type=sa.INTEGER(),
                       nullable=True)
        # Drop constraint only if exists
        fks = insp.get_foreign_keys('lectures')
        for fk in fks:
            if fk['name'] == 'lectures_course_id_fkey':
                op.drop_constraint('lectures_course_id_fkey', 'lectures', type_='foreignkey')
                op.create_foreign_key(None, 'lectures', 'courses', ['course_id'], ['id'], ondelete='SET NULL')

    if 'users' in tables:
        cols = insp.get_columns('users')
        pw_col = next((c for c in cols if c['name'] == 'hashed_password'), None)
        if pw_col and not pw_col['nullable']:
            op.alter_column('users', 'hashed_password',
                       existing_type=sa.TEXT(),
                       nullable=True)
        # Check indices and constraints for google_id
        idxs = insp.get_indexes('users')
        if not any(idx['name'] == 'ix_users_google_id' for idx in idxs):
            # Check for unique constraint before dropping
            try:
                op.drop_constraint('users_google_id_key', 'users', type_='unique')
            except Exception:
                pass
            op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)

    if 'news_articles' in tables:
        cols = {c['name'] for c in insp.get_columns('news_articles')}
        if 'author_name' not in cols:
            op.add_column('news_articles', sa.Column('author_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'author_name')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'lectures', type_='foreignkey')
    op.create_foreign_key('lectures_course_id_fkey', 'lectures', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('lectures', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('admin_permissions', 'admin_role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('super_admin', 'content_admin', 'finance_admin', 'support_admin', name='admin_role_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
