"""Add BatchDayTask model

Revision ID: 60f574e19344
Revises: 020_trading_sim_twelve_data
Create Date: 2026-07-04 06:51:28.851970
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60f574e19344'
down_revision: Union[str, None] = '020_trading_sim_twelve_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doubt_submissions_id', table_name='doubt_submissions')
    op.drop_table('doubt_submissions')
    op.drop_index('ix_doubt_forms_id', table_name='doubt_forms')
    op.drop_table('doubt_forms')
    op.alter_column('courses', 'is_batch_only',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'is_batch_only',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('doubt_forms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('doubt_forms_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name='doubt_forms_batch_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='doubt_forms_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='doubt_forms_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_doubt_forms_id', 'doubt_forms', ['id'], unique=False)
    op.create_table('doubt_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('doubt_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['doubt_forms.id'], name='doubt_submissions_form_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='doubt_submissions_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='doubt_submissions_pkey')
    )
    op.create_index('ix_doubt_submissions_id', 'doubt_submissions', ['id'], unique=False)
    # ### end Alembic commands ###
