"""auto_update

Revision ID: b27aa4a0eb6d
Revises: 026
Create Date: 2026-07-24 12:38:31.436329
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27aa4a0eb6d'
down_revision: Union[str, None] = '026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_batch_enrollments', 'access_blocked')
    op.add_column('user_devices', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_devices', sa.Column('last_active', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_devices', 'last_active')
    op.drop_column('user_devices', 'last_login')
    op.add_column('student_batch_enrollments', sa.Column('access_blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
