name: fintrade-backend-deploy

on:
  push:
    branches:
      - prd
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy Backend
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

            echo "---------------- Change Directory ----------------"
            cd ${{ secrets.WORK_DIR }}
            echo "---------------- Git Pull ----------------"
            git pull origin ${{ secrets.BRANCH }}

            echo "---------------- Install Pip ----------------"

            docker exec -i ${{ secrets.CONT_NAME }} pip install --upgrade pip

            echo "---------------- Install Requirements ----------------"

            docker exec -i ${{ secrets.CONT_NAME }} pip install -r requirements.txt

            echo "---------------- Alembic Migration ----------------"

            docker exec -i ${{ secrets.CONT_NAME }} python -m alembic upgrade head

            echo "---------------- Restart-------------------"

            docker restart ${{ secrets.CONT_NAME }}

            echo "---------------- Deployment Successful ----------------"

          EOF

      - name: Cleanup SSH
        run: |
          rm -rf ~/.ssh
